# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-08 01:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='course',
        ),
        migrations.RemoveField(
            model_name='form',
            name='questions',
        ),
        migrations.RemoveField(
            model_name='result',
            name='form',
        ),
        migrations.RemoveField(
            model_name='result',
            name='question',
        ),
        migrations.RemoveField(
            model_name='result',
            name='subject',
        ),
        migrations.DeleteModel(
            name='Form',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Result',
        ),
    ]
