# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-08 01:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20190408_0112'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='public_id',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
