# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-08 22:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_form_public_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('questions', models.ManyToManyField(blank=True, related_name='groups', to='data.Question')),
            ],
        ),
        migrations.RemoveField(
            model_name='form',
            name='questions',
        ),
        migrations.AddField(
            model_name='form',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='form',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='forms', to='data.Group'),
        ),
    ]
