# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-04 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_auto_20190504_1634'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AddField(
            model_name='group',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
